export const ADD_TABOO_WORD_REQUEST = 'ADD_TABOO_WORD_REQUEST';
export const ADD_TABOO_WORD_SUCCESS = 'ADD_TABOO_WORD_SUCCESS';
export const ADD_TABOO_WORD_FAIL = 'ADD_TABOO_WORD_FAIL';

export const GET_TABOO_WORDS_REQUEST = 'GET_TABOO_WORDS_REQUEST';
export const GET_TABOO_WORDS_SUCCESS = 'GET_TABOO_WORDS_SUCCESS';
export const GET_TABOO_WORDS_FAIL = 'GET_TABOO_WORDS_FAIL';
