export const ADD_TABOO_WORD_REQUEST = "ADD_TABOO_WORD_REQUEST";
export const ADD_TABOO_WORD_SUCCESS = "ADD_TABOO_WORD_SUCCESS";
export const ADD_TABOO_WORD_FAIL = "ADD_TABOO_WORD_FAIL";

export const GET_TABOO_WORDS_REQUEST = "GET_TABOO_WORDS_REQUEST";
export const GET_TABOO_WORDS_SUCCESS = "GET_TABOO_WORDS_SUCCESS";
export const GET_TABOO_WORDS_FAIL = "GET_TABOO_WORDS_FAIL";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const GET_DISCISSION_REQUEST = "GET_DISCISSION_REQUEST";
export const GET_DISCISSION_SUCCESS = "GET_DISCISSION_SUCCESS";
export const GET_DISCISSION_FAIL = "GET_DISCISSION_FAIL";

export const DELETE_TABOO_WORD_REQUEST = "DELETE_TABOO_WORD_REQUEST";
export const DELETE_TABOO_WORD_SUCCESS = "DELETE_TABOO_WORD_SUCCESS";
export const DELETE_TABOO_WORD_FAIL = "DELETE_TABOO_WORD_FAIL";
