const data = {
  products: [
    {
      _id: '1',
      name: 'Corsair RMX Series',
      category: 'Power Supply',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Corsair',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Corsair RMX Series',
      category: 'Power Supply',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Corsair',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Corsair RMX Series',
      category: 'Power Supply',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Corsair',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Corsair RMX Series',
      category: 'Power Supply',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Corsair',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Corsair RMX Series',
      category: 'Power Supply',
      image: '/images/p5.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Corsair',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Corsair RMX Series',
      category: 'Power Supply',
      image: '/images/p6.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Corsair',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    
  ],
};
export default data;
